//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIDRS.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IIDRSEntities : DbContext
    {
        public IIDRSEntities()
            : base("name=IIDRSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<M_ADDR_PER> M_ADDR_PER { get; set; }
        public virtual DbSet<M_BU> M_BU { get; set; }
        public virtual DbSet<M_CONTACT> M_CONTACT { get; set; }
        public virtual DbSet<M_CUST_SURVEY> M_CUST_SURVEY { get; set; }
        public virtual DbSet<M_ORG_EXT> M_ORG_EXT { get; set; }
        public virtual DbSet<M_PARTY> M_PARTY { get; set; }
        public virtual DbSet<M_POSTN> M_POSTN { get; set; }
        public virtual DbSet<M_USER> M_USER { get; set; }
        public virtual DbSet<M_ZIPCODE> M_ZIPCODE { get; set; }
        public virtual DbSet<Vw_User> Vw_User { get; set; }
    }
}
