//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIDRS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_ADDR_PER
    {
        public string ROW_ID { get; set; }
        public string PERSON_UID { get; set; }
        public string ADDR { get; set; }
        public string ADDR_LINE_2 { get; set; }
        public string ADDR_LINE_3 { get; set; }
        public string ADDR_FLG { get; set; }
        public string CITY { get; set; }
        public string COUNTRY { get; set; }
        public string STATE { get; set; }
        public string ZIPCODE { get; set; }
        public string COMMENTS { get; set; }
        public Nullable<System.DateTime> CREATED_DT { get; set; }
        public string CREATED_BY { get; set; }
        public string LAST_UPD_DT { get; set; }
        public string LAST_UPD_BY { get; set; }
    }
}
