//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIDRS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_BU
    {
        public string ROW_ID { get; set; }
        public string BU_ID { get; set; }
        public string PAR_BU_ID { get; set; }
        public string BU_NAME { get; set; }
        public string BU_FLG { get; set; }
        public string BU_TYPE { get; set; }
        public string PAR_ROW_ID { get; set; }
        public string DU_NAME { get; set; }
        public string PROJ_ID { get; set; }
        public string PROJ_NAME { get; set; }
        public Nullable<System.DateTime> CREATED_DT { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPD_DT { get; set; }
        public string LAST_UPD_BY { get; set; }
    }
}
