//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIDRS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_CUST_SURVEY
    {
        public string ROW_ID { get; set; }
        public string SURVEY_ID { get; set; }
        public string PAR_ROW_ID { get; set; }
        public string CUST_SURVEY_NAME { get; set; }
        public string SURVEY_QUESTION_NAME { get; set; }
        public string SURVEY_QUESTION_DESC { get; set; }
        public string SURVEY_FLG { get; set; }
        public Nullable<System.DateTime> CREATED_DT { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPD_DT { get; set; }
        public string LAST_UPD_BY { get; set; }
    }
}
