//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIDRS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_ORG_EXT
    {
        public string ROW_ID { get; set; }
        public string NAME { get; set; }
        public string LOC { get; set; }
        public string BU_ID { get; set; }
        public string ACCNT_FLG { get; set; }
        public string ACTIVE_FLG { get; set; }
        public string PAR_ROW_ID { get; set; }
        public Nullable<System.DateTime> CUST_END_DT { get; set; }
        public Nullable<System.DateTime> CUST_SINCE_DT { get; set; }
        public string PAR_BU_ID { get; set; }
        public string PARTNER_FLG { get; set; }
        public string PAR_DIVN_ID { get; set; }
        public string PR_ADDR_ID { get; set; }
        public string PR_ADDR_PER_ID { get; set; }
        public string PR_BL_ADDR_ID { get; set; }
        public string PR_BL_PER_ID { get; set; }
        public string PR_CON_ID { get; set; }
        public string PR_POSTN_ID { get; set; }
        public string SURVEY_ID { get; set; }
        public string RATING { get; set; }
        public string ZIPCODE { get; set; }
        public Nullable<System.DateTime> CREATED_DT { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPD_DT { get; set; }
        public string LAST_UPD_BY { get; set; }
    }
}
