//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIDRS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_PARTY
    {
        public string PARTY_UID { get; set; }
        public string PARTY_TYPE_CD { get; set; }
        public string TRANS_FLG { get; set; }
        public string ACTIVE_FLG { get; set; }
        public Nullable<System.DateTime> CREATED_DT { get; set; }
        public Nullable<System.DateTime> LAST_UPD_DT { get; set; }
    }
}
