//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIDRS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_USER
    {
        public string USER_ID { get; set; }
        public string LOGIN { get; set; }
        public string LOGIN_DOMAIN { get; set; }
        public string PAR_ROW_ID { get; set; }
        public string USER_FLG { get; set; }
        public string CHALLENGE_ANSWER { get; set; }
        public string CHALLENGE_QUESTION { get; set; }
        public string CTI_ACD_USERID { get; set; }
        public string CTI_PWD { get; set; }
        public string EXCHNG_PROF_NAME { get; set; }
        public string EXCHNG_PROF_PWD { get; set; }
        public string EXCHNG_STOREID { get; set; }
        public string EXCHNG_SYNC_TYPE { get; set; }
        public string PASSWORD { get; set; }
        public string PW_LAST_UPD { get; set; }
        public string RPT_SRVR_PWD { get; set; }
        public Nullable<System.DateTime> CREATED_DT { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPD_DT { get; set; }
        public string LAST_UPD_BY { get; set; }
        public string PERSON_UID { get; set; }
        public string BU_ID { get; set; }
    }
}
