//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIDRS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_User
    {
        public string LoginID { get; set; }
        public string LOGIN { get; set; }
        public string LOGIN_DOMAIN { get; set; }
        public string USER_FLG { get; set; }
        public string Contact_Person { get; set; }
        public string Email { get; set; }
        public string EMP_ID { get; set; }
        public string PHONE_NO { get; set; }
        public string BU_TYPE { get; set; }
        public string DU { get; set; }
        public string ProjectID { get; set; }
        public string ProjectName { get; set; }
        public string BRAND { get; set; }
        public string BU_ID { get; set; }
        public string PERSON_UID { get; set; }
        public string zipcode { get; set; }
    }
}
