USE [IDRS]
GO

/****** Object:  Table [dbo].[M_BU]    Script Date: 29-09-2020 00:34:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[M_BU](
	[ROW_ID] [varchar](50) NOT NULL,
	[BU_ID] [varchar](50) NOT NULL,
	[PAR_BU_ID] [varchar](50) NULL,
	[BU_NAME] [varchar](50) NULL,
	[BU_FLG] [varchar](50) NULL,
	[BU_TYPE] [varchar](50) NULL,
	[PAR_ROW_ID] [varchar](50) NULL,
	[DU_NAME] [varchar](50) NULL,
	[PROJ_ID] [varchar](50) NULL,
	[PROJ_NAME] [varchar](50) NULL,
	[CREATED_DT] [datetime] NULL,
	[CREATED_BY] [varchar](50) NULL,
	[LAST_UPD_DT] [datetime] NULL,
	[LAST_UPD_BY] [varchar](50) NULL,
 CONSTRAINT [PK_M_BU] PRIMARY KEY CLUSTERED 
(
	[BU_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


