USE [IDRS]
GO

/****** Object:  Table [dbo].[M_PARTY]    Script Date: 29-09-2020 00:33:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[M_PARTY](
	[PARTY_UID] [varchar](50) NOT NULL,
	[PARTY_TYPE_CD] [varchar](50) NOT NULL,
	[TRANS_FLG] [varchar](50) NULL,
	[ACTIVE_FLG] [varchar](50) NULL,
	[CREATED_DT] [datetime] NULL,
	[LAST_UPD_DT] [datetime] NULL,
 CONSTRAINT [PK_M_PARTY] PRIMARY KEY CLUSTERED 
(
	[PARTY_TYPE_CD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


