USE [IDRS]
GO

/****** Object:  Table [dbo].[M_POSTN]    Script Date: 29-09-2020 00:33:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[M_POSTN](
	[ROW_ID] [varchar](50) NOT NULL,
	[BU_ID] [varchar](50) NOT NULL,
	[POSTN_TYPE_CD] [varchar](50) NOT NULL,
	[POSTN_NAME] [varchar](50) NULL,
	[CREATED_DT] [datetime] NULL,
	[CREATED_BY] [varchar](50) NULL,
	[LAST_UPD_DT] [datetime] NULL,
	[LAST_UPD_BY] [varchar](50) NULL,
 CONSTRAINT [PK_M_POSTN] PRIMARY KEY CLUSTERED 
(
	[POSTN_TYPE_CD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


